### PR TITLE
Fix esify eslint

### LINKED ISSUE #185: ESLint is not actually running
My fix to ESLint broke it. Trying to do the right thing locally results in some crazy require-related errors, which I think relate to the babel stuff we do in `shopify-codemod`.

### PR DESCRIPTION
**Pull request by TylerHorth**
Attempt to load local eslint and process with --fix. 

Fixes #185 

@lemonmade @GoodForOneFare

### CODE REVIEW

**Comment by lemonmade** [comment]
Code looks good 👍 

Can you check what the compile times before/ after are for a large-ish set of files (maybe try 10–20)? I want to make sure we don't regress too much on that measure.

**Comment by GoodForOneFare** [comment]
🎩 went well, code's good.  🚢 assuming there isn't a significant perf regression.

**Comment by TylerHorth** [comment]
I ran it on all coffeescript files in `assets/javascripts/admin/modules/products/` (~30 files), there wasn't a significant regression:

|eslint|real|user|sys|
|-----|----|----|----|
|NO|34.53s|30.72s|22.85s|
|YES|38.34s|34.60s|23.01s|

@lemonmade @GoodForOneFare 🚢 ?

**Comment by GoodForOneFare** [comment]
So, like, ~125ms/file?  For the use case of many people updating one file at a time, looks worth it to me.

**Comment by lemonmade** [comment]
🐑

**Pull request merged**
