### PR TITLE
Make esify an installable binary

### PR DESCRIPTION
**Pull request by lemonmade**
This adds `esify` as an actual project into the JS repo, and moves things around so that it can work by being installed globally and running `esify path/to/file.coffee` from the root of the Shopify repo.

cc/ @GoodForOneFare @bouk

### CODE REVIEW

**Comment by bouk** [comment]
We probably shouldn't commit the compiled code

**Comment by lemonmade** [comment]
Yeah, I rolled back the compiling stuff because the other transforms we use need babel to work properly anyways :(

**Comment by GoodForOneFare** [comment]
Does this belong in here?  It seems like we'll just delete it once the conversion is complete.

**Comment by GoodForOneFare** [comment]
Code LGTM, and 🎩 went well.

Note that I couldn't lint this; if I roll back to before @d0ab34203de7fc25aa0bd476548de130e7df1faa, things work again.

**Comment by lemonmade** [comment]
@GoodForOneFare I think it's fine in here, simplifies how many repos we have and we can just delete it once it's no longer useful. I think the linting issues will probably go away with a fresh `script/setup`.

**Pull request merged**
